{application,idler,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{idler_app,[]}},
              {env,[]},
              {modules,[config,connection,connection_sup,connectionhelper,
                        idler_app,idler_sup,ircmsg]}]}.
